### ISSUE TITLE
last line is not annotated

### ISSUE THREAD

**Issue by NanaGlutamate** [JamiLu/simply-blame#15] opened 2024-08-13 03:17 UTC
if last line is not empty line, it looks wierd

**Comment by JamiLu** [comment] 2024-08-13 10:59
Maybe if you could attach a screenshot here, please :)

**Comment by NanaGlutamate** [comment] 2024-08-14 06:34
<img width="329" alt="image" src="https://github.com/user-attachments/assets/4afcce35-0147-4742-98e4-ca19bb8179ce">
thanks for your efforts

**Comment by JamiLu** [comment] 2024-08-14 21:43
The issue is now fixed in the release 0.0.6 https://github.com/JamiLu/simply-blame/releases/tag/0.0.6

**Closed by JamiLu** 2024-08-14 21:43 UTC
