### ISSUE TITLE
Does not work (On Win11)

### ISSUE THREAD

**Issue by crytt** [JamiLu/simply-blame#1] opened 2024-06-03 09:14 UTC
> Command failed: cd /c:/src/app/ && git blame c:\src\app\src\components\Component.tsx 
> The filename, directory name, or volume label syntax is incorrect.

It seems to not work on my Win 10 machine. 

Most likely due to the mixed use of forward and backward slashes.

**Comment by JamiLu** [comment] 2024-06-04 11:11
Hi. Thank you for your posting this issue. Yes this issue is kind of a known issue. I haven't yet had time to fix it. But I'll definitely fix this as soon as I get the time.

**Comment by JamiLu** [comment] 2024-07-08 20:10
Update, this will be my next thing to fix. :)

**Comment by JamiLu** [comment] 2024-07-09 09:46
I will make a new release today that will fix this issue. Stay tuned.

**Comment by JamiLu** [comment] 2024-07-09 14:31
The version 0.0.3 is now released https://github.com/JamiLu/simply-blame/releases/tag/0.0.3. The issue is now fixed.

**Closed by JamiLu** 2024-07-09 14:31 UTC
